################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/HawkUtil/HawkApp.cpp \
../src/HawkUtil/HawkAppObj.cpp \
../src/HawkUtil/HawkBase64.cpp \
../src/HawkUtil/HawkBinCfgFile.cpp \
../src/HawkUtil/HawkCounter.cpp \
../src/HawkUtil/HawkDBManager.cpp \
../src/HawkUtil/HawkDatabase.cpp \
../src/HawkUtil/HawkDiskFile.cpp \
../src/HawkUtil/HawkException.cpp \
../src/HawkUtil/HawkFile.cpp \
../src/HawkUtil/HawkFileAcceptor.cpp \
../src/HawkUtil/HawkFileSender.cpp \
../src/HawkUtil/HawkFolder.cpp \
../src/HawkUtil/HawkHMACSHA1Security.cpp \
../src/HawkUtil/HawkIPAddr.cpp \
../src/HawkUtil/HawkJson.cpp \
../src/HawkUtil/HawkKVFile.cpp \
../src/HawkUtil/HawkLogger.cpp \
../src/HawkUtil/HawkLoggerManager.cpp \
../src/HawkUtil/HawkLuaApi.cpp \
../src/HawkUtil/HawkMalloc.cpp \
../src/HawkUtil/HawkManagerBase.cpp \
../src/HawkUtil/HawkMarshal.cpp \
../src/HawkUtil/HawkMarshalData.cpp \
../src/HawkUtil/HawkMath.cpp \
../src/HawkUtil/HawkMd5.cpp \
../src/HawkUtil/HawkMemoryFile.cpp \
../src/HawkUtil/HawkMsg.cpp \
../src/HawkUtil/HawkMsgListener.cpp \
../src/HawkUtil/HawkMsgManager.cpp \
../src/HawkUtil/HawkMsgPump.cpp \
../src/HawkUtil/HawkMutex.cpp \
../src/HawkUtil/HawkMysql.cpp \
../src/HawkUtil/HawkOSOperator.cpp \
../src/HawkUtil/HawkObjBase.cpp \
../src/HawkUtil/HawkObjManager.cpp \
../src/HawkUtil/HawkOctets.cpp \
../src/HawkUtil/HawkOctetsStream.cpp \
../src/HawkUtil/HawkPackage.cpp \
../src/HawkUtil/HawkParamVector.cpp \
../src/HawkUtil/HawkProtocol.cpp \
../src/HawkUtil/HawkProtocolGen-Cpp.cpp \
../src/HawkUtil/HawkProtocolGen-Flash.cpp \
../src/HawkUtil/HawkProtocolGen-Java.cpp \
../src/HawkUtil/HawkProtocolGen-Lua.cpp \
../src/HawkUtil/HawkProtocolGen.cpp \
../src/HawkUtil/HawkProtocolListener.cpp \
../src/HawkUtil/HawkProtocolManager.cpp \
../src/HawkUtil/HawkProtocolPump.cpp \
../src/HawkUtil/HawkRC4Security.cpp \
../src/HawkUtil/HawkRWEFds.cpp \
../src/HawkUtil/HawkRWLock.cpp \
../src/HawkUtil/HawkRand.cpp \
../src/HawkUtil/HawkRefCounter.cpp \
../src/HawkUtil/HawkSHA1Security.cpp \
../src/HawkUtil/HawkScope.cpp \
../src/HawkUtil/HawkScriptState.cpp \
../src/HawkUtil/HawkScriptValue.cpp \
../src/HawkUtil/HawkSecurity.cpp \
../src/HawkUtil/HawkSession.cpp \
../src/HawkUtil/HawkSignal.cpp \
../src/HawkUtil/HawkSocket.cpp \
../src/HawkUtil/HawkSocketAddr.cpp \
../src/HawkUtil/HawkSocketPair.cpp \
../src/HawkUtil/HawkSpinLock.cpp \
../src/HawkUtil/HawkSqlite.cpp \
../src/HawkUtil/HawkStreamCompress.cpp \
../src/HawkUtil/HawkStringUtil.cpp \
../src/HawkUtil/HawkTask.cpp \
../src/HawkUtil/HawkThread.cpp \
../src/HawkUtil/HawkThreadPool.cpp \
../src/HawkUtil/HawkTimerManager.cpp \
../src/HawkUtil/HawkUtil.cpp \
../src/HawkUtil/HawkWebSocket.cpp \
../src/HawkUtil/HawkXmlFile.cpp \
../src/HawkUtil/HawkXorSecurity.cpp \
../src/HawkUtil/HawkZipReader.cpp \
../src/HawkUtil/HawkZlib.cpp \
../src/HawkUtil/HawkZmq.cpp \
../src/HawkUtil/HawkZmqManager.cpp 

OBJS += \
./src/HawkUtil/HawkApp.o \
./src/HawkUtil/HawkAppObj.o \
./src/HawkUtil/HawkBase64.o \
./src/HawkUtil/HawkBinCfgFile.o \
./src/HawkUtil/HawkCounter.o \
./src/HawkUtil/HawkDBManager.o \
./src/HawkUtil/HawkDatabase.o \
./src/HawkUtil/HawkDiskFile.o \
./src/HawkUtil/HawkException.o \
./src/HawkUtil/HawkFile.o \
./src/HawkUtil/HawkFileAcceptor.o \
./src/HawkUtil/HawkFileSender.o \
./src/HawkUtil/HawkFolder.o \
./src/HawkUtil/HawkHMACSHA1Security.o \
./src/HawkUtil/HawkIPAddr.o \
./src/HawkUtil/HawkJson.o \
./src/HawkUtil/HawkKVFile.o \
./src/HawkUtil/HawkLogger.o \
./src/HawkUtil/HawkLoggerManager.o \
./src/HawkUtil/HawkLuaApi.o \
./src/HawkUtil/HawkMalloc.o \
./src/HawkUtil/HawkManagerBase.o \
./src/HawkUtil/HawkMarshal.o \
./src/HawkUtil/HawkMarshalData.o \
./src/HawkUtil/HawkMath.o \
./src/HawkUtil/HawkMd5.o \
./src/HawkUtil/HawkMemoryFile.o \
./src/HawkUtil/HawkMsg.o \
./src/HawkUtil/HawkMsgListener.o \
./src/HawkUtil/HawkMsgManager.o \
./src/HawkUtil/HawkMsgPump.o \
./src/HawkUtil/HawkMutex.o \
./src/HawkUtil/HawkMysql.o \
./src/HawkUtil/HawkOSOperator.o \
./src/HawkUtil/HawkObjBase.o \
./src/HawkUtil/HawkObjManager.o \
./src/HawkUtil/HawkOctets.o \
./src/HawkUtil/HawkOctetsStream.o \
./src/HawkUtil/HawkPackage.o \
./src/HawkUtil/HawkParamVector.o \
./src/HawkUtil/HawkProtocol.o \
./src/HawkUtil/HawkProtocolGen-Cpp.o \
./src/HawkUtil/HawkProtocolGen-Flash.o \
./src/HawkUtil/HawkProtocolGen-Java.o \
./src/HawkUtil/HawkProtocolGen-Lua.o \
./src/HawkUtil/HawkProtocolGen.o \
./src/HawkUtil/HawkProtocolListener.o \
./src/HawkUtil/HawkProtocolManager.o \
./src/HawkUtil/HawkProtocolPump.o \
./src/HawkUtil/HawkRC4Security.o \
./src/HawkUtil/HawkRWEFds.o \
./src/HawkUtil/HawkRWLock.o \
./src/HawkUtil/HawkRand.o \
./src/HawkUtil/HawkRefCounter.o \
./src/HawkUtil/HawkSHA1Security.o \
./src/HawkUtil/HawkScope.o \
./src/HawkUtil/HawkScriptState.o \
./src/HawkUtil/HawkScriptValue.o \
./src/HawkUtil/HawkSecurity.o \
./src/HawkUtil/HawkSession.o \
./src/HawkUtil/HawkSignal.o \
./src/HawkUtil/HawkSocket.o \
./src/HawkUtil/HawkSocketAddr.o \
./src/HawkUtil/HawkSocketPair.o \
./src/HawkUtil/HawkSpinLock.o \
./src/HawkUtil/HawkSqlite.o \
./src/HawkUtil/HawkStreamCompress.o \
./src/HawkUtil/HawkStringUtil.o \
./src/HawkUtil/HawkTask.o \
./src/HawkUtil/HawkThread.o \
./src/HawkUtil/HawkThreadPool.o \
./src/HawkUtil/HawkTimerManager.o \
./src/HawkUtil/HawkUtil.o \
./src/HawkUtil/HawkWebSocket.o \
./src/HawkUtil/HawkXmlFile.o \
./src/HawkUtil/HawkXorSecurity.o \
./src/HawkUtil/HawkZipReader.o \
./src/HawkUtil/HawkZlib.o \
./src/HawkUtil/HawkZmq.o \
./src/HawkUtil/HawkZmqManager.o 

CPP_DEPS += \
./src/HawkUtil/HawkApp.d \
./src/HawkUtil/HawkAppObj.d \
./src/HawkUtil/HawkBase64.d \
./src/HawkUtil/HawkBinCfgFile.d \
./src/HawkUtil/HawkCounter.d \
./src/HawkUtil/HawkDBManager.d \
./src/HawkUtil/HawkDatabase.d \
./src/HawkUtil/HawkDiskFile.d \
./src/HawkUtil/HawkException.d \
./src/HawkUtil/HawkFile.d \
./src/HawkUtil/HawkFileAcceptor.d \
./src/HawkUtil/HawkFileSender.d \
./src/HawkUtil/HawkFolder.d \
./src/HawkUtil/HawkHMACSHA1Security.d \
./src/HawkUtil/HawkIPAddr.d \
./src/HawkUtil/HawkJson.d \
./src/HawkUtil/HawkKVFile.d \
./src/HawkUtil/HawkLogger.d \
./src/HawkUtil/HawkLoggerManager.d \
./src/HawkUtil/HawkLuaApi.d \
./src/HawkUtil/HawkMalloc.d \
./src/HawkUtil/HawkManagerBase.d \
./src/HawkUtil/HawkMarshal.d \
./src/HawkUtil/HawkMarshalData.d \
./src/HawkUtil/HawkMath.d \
./src/HawkUtil/HawkMd5.d \
./src/HawkUtil/HawkMemoryFile.d \
./src/HawkUtil/HawkMsg.d \
./src/HawkUtil/HawkMsgListener.d \
./src/HawkUtil/HawkMsgManager.d \
./src/HawkUtil/HawkMsgPump.d \
./src/HawkUtil/HawkMutex.d \
./src/HawkUtil/HawkMysql.d \
./src/HawkUtil/HawkOSOperator.d \
./src/HawkUtil/HawkObjBase.d \
./src/HawkUtil/HawkObjManager.d \
./src/HawkUtil/HawkOctets.d \
./src/HawkUtil/HawkOctetsStream.d \
./src/HawkUtil/HawkPackage.d \
./src/HawkUtil/HawkParamVector.d \
./src/HawkUtil/HawkProtocol.d \
./src/HawkUtil/HawkProtocolGen-Cpp.d \
./src/HawkUtil/HawkProtocolGen-Flash.d \
./src/HawkUtil/HawkProtocolGen-Java.d \
./src/HawkUtil/HawkProtocolGen-Lua.d \
./src/HawkUtil/HawkProtocolGen.d \
./src/HawkUtil/HawkProtocolListener.d \
./src/HawkUtil/HawkProtocolManager.d \
./src/HawkUtil/HawkProtocolPump.d \
./src/HawkUtil/HawkRC4Security.d \
./src/HawkUtil/HawkRWEFds.d \
./src/HawkUtil/HawkRWLock.d \
./src/HawkUtil/HawkRand.d \
./src/HawkUtil/HawkRefCounter.d \
./src/HawkUtil/HawkSHA1Security.d \
./src/HawkUtil/HawkScope.d \
./src/HawkUtil/HawkScriptState.d \
./src/HawkUtil/HawkScriptValue.d \
./src/HawkUtil/HawkSecurity.d \
./src/HawkUtil/HawkSession.d \
./src/HawkUtil/HawkSignal.d \
./src/HawkUtil/HawkSocket.d \
./src/HawkUtil/HawkSocketAddr.d \
./src/HawkUtil/HawkSocketPair.d \
./src/HawkUtil/HawkSpinLock.d \
./src/HawkUtil/HawkSqlite.d \
./src/HawkUtil/HawkStreamCompress.d \
./src/HawkUtil/HawkStringUtil.d \
./src/HawkUtil/HawkTask.d \
./src/HawkUtil/HawkThread.d \
./src/HawkUtil/HawkThreadPool.d \
./src/HawkUtil/HawkTimerManager.d \
./src/HawkUtil/HawkUtil.d \
./src/HawkUtil/HawkWebSocket.d \
./src/HawkUtil/HawkXmlFile.d \
./src/HawkUtil/HawkXorSecurity.d \
./src/HawkUtil/HawkZipReader.d \
./src/HawkUtil/HawkZlib.d \
./src/HawkUtil/HawkZmq.d \
./src/HawkUtil/HawkZmqManager.d 


# Each subdirectory must supply rules for building sources it contributes
src/HawkUtil/%.o: ../src/HawkUtil/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0  -std=gnu++11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


